In [1]:
import os
import sys
import pandas as pd
import numpy as np

# Load data

In [2]:
data_path = os.path.join('..', 'data', 'train.csv')

data = pd.read_csv(data_path)

C:\Users\PC\AppData\Local\Temp\ipykernel_19544\1615417973.py:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(data_path)

In [3]:
data.head(3)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [5]:
# Add project root to path
project_root = os.path.abspath(os.path.join(".."))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.Preprocessor import (
    DataCleaner,
    NumericCleaner,
    NegativeValueHandler,
    CreditAgeParser,
    LoanTypeEncoder,
    CategoricalEncoder,
    TargetEncoder,
)
from sklearn.pipeline import Pipeline

In [6]:
# Define column lists
numeric_cols = [
    "Annual_Income",
    "Monthly_Inhand_Salary",
    "Num_Bank_Accounts",
    "Num_Credit_Card",
    "Interest_Rate",
    "Num_of_Loan",
    "Delay_from_due_date",
    "Num_of_Delayed_Payment",
    "Changed_Credit_Limit",
    "Num_Credit_Inquiries",
    "Outstanding_Debt",
    "Credit_Utilization_Ratio",
    "Total_EMI_per_month",
    "Amount_invested_monthly",
    "Monthly_Balance",
]

# Handle negative values
invalid_cols = [
    "Annual_Income",
    "Monthly_Inhand_Salary",
    "Num_Bank_Accounts",
    "Num_Credit_Card",
    "Interest_Rate",
    "Num_of_Loan",
    "Delay_from_due_date",
    "Num_of_Delayed_Payment",
    "Num_Credit_Inquiries",
    "Outstanding_Debt",
    "Credit_Utilization_Ratio",
    "Credit_History_Age",
    "Total_EMI_per_month",
]

categorical_cols = ["Occupation", "Credit_Mix", "Payment_of_Min_Amount", "Payment_Behaviour"]

# Create preprocessing pipeline
preprocessing_pipeline = Pipeline(
    [
        ("data_cleaner", DataCleaner()),
        ("numeric_cleaner", NumericCleaner(numeric_cols)),
        ("credit_age_parser", CreditAgeParser()),
        ("loan_encoder", LoanTypeEncoder()),
        ("categorical_encoder", CategoricalEncoder(categorical_cols)),
        ("target_encoder", TargetEncoder()),
        ("negative_value_handler", NegativeValueHandler(invalid_cols)),
    ]
)

In [7]:
data['Num_of_Delayed_Payment'].unique()

array(['7', nan, '4', '8_', '6', '1', '-1', '3_', '0', '8', '5', '3', '9',
       '12', '15', '17', '10', '2', '2_', '11', '14', '20', '22', '13',
       '13_', '14_', '16', '12_', '18', '19', '23', '24', '21', '3318',
       '3083', '22_', '1338', '4_', '26', '11_', '3104', '21_', '25',
       '10_', '183_', '9_', '1106', '834', '19_', '24_', '17_', '23_',
       '2672', '20_', '2008', '-3', '538', '6_', '1_', '16_', '27', '-2',
       '3478', '2420', '15_', '707', '708', '26_', '18_', '3815', '28',
       '5_', '1867', '2250', '1463', '25_', '7_', '4126', '2882', '1941',
       '2655', '2628', '132', '3069', '306', '0_', '3539', '3684', '1823',
       '4128', '1946', '827', '2297', '2566', '904', '182', '929', '3568',
       '2503', '1552', '2812', '1697', '3764', '851', '3905', '923', '88',
       '1668', '3253', '808', '2689', '3858', '642', '3457', '1402',
       '1732', '3154', '847', '3037', '2204', '3103', '1063', '2056',
       '1282', '1841', '2569_', '211', '793', '3484', '411', '3491',
       '2072', '3050', '1049', '2162', '3402', '2753', '27_', '1718',
       '1014', '3260', '3855', '84', '2311', '3251', '1832', '4069',
       '3010', '733', '4241', '166', '2461', '1749', '3200', '663_',
       '2185', '4161', '3009', '359', '2015', '1523', '594', '1079',
       '1199', '186', '1015', '1989', '281', '559', '2165', '1509',
       '3545', '779', '192', '4311', '-2_', '2323', '1471', '1538',
       '3529', '439', '3456', '3040', '2697', '3179', '1332', '3175',
       '3112', '829', '4022', '3870', '4023', '531', '1511', '3092',
       '3191', '2400', '3621', '3536', '544', '1864', '28_', '142',
       '2300', '264', '72', '497', '398', '2222', '3960', '1473', '3043',
       '4216', '2903', '2658', '-1_', '4042', '1323_', '2184', '921',
       '1328', '3404', '2438', '809', '47', '1996', '4164', '1370',
       '1204', '2167', '4011', '2590', '2594', '2533', '1663', '1018',
       '2919', '3458', '3316', '2589', '2801', '3355', '2529', '2488',
       '4266', '1243', '739', '845', '4107', '1884', '337', '2660', '290',
       '674', '2450', '3738', '1792', '2823', '2570', '775', '960', '482',
       '1706', '2493', '3623', '3031', '2794_', '2219_', '758_', '1849',
       '3559', '4096', '3726', '1953', '2657', '4043', '2938', '4384',
       '1647', '2694', '3533', '519', '2677', '2413', '-3_', '4139',
       '2609', '4326', '4211', '823', '3011', '1608', '2860', '4219',
       '4047', '1531', '742', '52', '4024', '1673', '49', '2243', '1685',
       '1869', '2587', '3489', '749', '1164', '2616', '848_', '4134',
       '1530', '1502', '4075', '3845', '1060', '2573', '2128', '328',
       '640', '2585', '2230', '1795', '1180', '1534', '3739', '3313',
       '4191', '996', '372', '3340', '3177', '602', '787', '4135', '3878',
       '4059', '1218', '4051', '1766', '1359', '3107', '585', '1263',
       '2511', '709', '3632', '4077', '2943', '2793', '3245', '2317',
       '1640', '2237_', '3819', '252', '3978', '1498', '1833', '2737',
       '1192', '1481', '700', '271', '2286', '273', '1215', '3944',
       '2070', '1478', '3749', '871', '2508', '2959', '130', '294',
       '3097_', '3511', '415', '2196', '2138', '2149', '1874', '1553',
       '3847', '3222', '1222', '2907', '3051', '98', '1598', '416',
       '2314', '2955', '1691', '1450', '2021', '1636', '80', '3708',
       '195', '320', '2945', '1911', '3416', '3796', '4159', '2255',
       '938', '4397', '3776', '2148', '1994', '853', '1178', '1633',
       '196', '3864', '714', '1687', '1034', '468', '1337', '2044',
       '1541', '3661', '1211', '2645', '2007', '102', '1891', '3162',
       '3142', '2566_', '2766', '3881', '2728', '2671', '1952', '3580',
       '2705', '4251', '3840_', '972', '3119', '3502', '4185', '2954',
       '683', '1614', '1572', '4302', '3447', '1852', '2131', '1900',
       '1699', '133', '2018', '2127', '508', '210', '577', '1664', '2604',
       '1411', '2351', '867', '1371', '2352', '1191', '905', '4053',
       '3869', '933', '3660', '3300', '3629', '3208', '2142', '2521',
       '450', '583', '876', '121', '3919', '2560', '2578', '2060', '813',
       '1236', '1489', '4360', '1154', '2544', '4172', '2924', '426',
       '4270', '2768', '3909', '3951', '2712', '2498', '3171', '1750',
       '197', '2569', '265', '4293', '887', '2707', '2397', '4337',
       '4249', '2751', '2950', '1859', '107', '2348', '2506', '2810',
       '2873', '1301', '2262', '1890', '3078', '3865', '3268', '2777',
       '3105', '1278', '3793', '2276', '2879', '4298', '2141', '223',
       '2239', '846', '1862', '2756', '1181', '1184', '2617', '3972',
       '2334', '3900', '2759', '4169', '2280', '2492', '2729', '3750',
       '1825', '309', '2431', '3099', '2080', '2279', '2666', '3722',
       '1976', '529', '1985', '3060', '4278', '3212', '46', '3148',
       '3467', '4231', '3790', '473', '1536', '3955', '2324', '2381',
       '1177', '371', '2896', '3880', '2991', '4319', '1061', '662',
       '4144', '693', '2006', '3115', '2278_', '3751', '1861', '4262',
       '2913', '2615', '3492', '800', '3766', '384', '3407', '1087',
       '3329', '1086', '2216', '1087_', '2457', '3522', '3274', '3488',
       '2854', '238', '351', '3706', '4280', '4095', '2926', '1329',
       '3370', '283', '1392', '1743', '2429', '974', '3156', '1133',
       '4388', '3243', '4282', '2523', '4281', '3415', '2001', '441',
       '94', '3499', '969', '3368', '106', '1004', '2638', '3946', '2956',
       '4324', '85', '4113', '819', '615', '1172', '2553', '1765', '3495',
       '2820', '4239', '4340', '1295_', '2636', '4295', '1653', '1325',
       '1879', '1096', '1735', '3584', '1073', '1975', '3827', '2552',
       '3754', '2378', '532', '926', '2376', '3636', '3763', '778',
       '2621', '804', '754', '2418', '4019', '3926', '3861_', '3574',
       '175', '162', '2834', '3765', '2354', '523', '2274', '1606',
       '1443', '1354', '2142_', '1422', '2278', '1045', '4106', '3155',
       '666', '659', '3229', '1216', '2076', '1473_', '2384', '1954',
       '719', '2534', '4002', '541', '2875', '4344', '2081', '3894',
       '1256', '676', '4178', '399', '86', '1571', '4037', '1967', '4005',
       '3216', '1150', '2591', '1801', '3721', '1775', '2260', '3707',
       '4292', '1820', '145', '1480', '1850', '430', '217', '3920_',
       '1389', '1579', '3391', '2385', '3336', '3392', '3688', '221',
       '2047'], dtype=object)

In [8]:
processed = preprocessing_pipeline.fit_transform(data)

In [13]:
processed.head(3)

,ID,Customer_ID,Month,Name,Age,SSN,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,...,Credit_Mix_nan,Credit_Mix_standard,Payment_of_Min_Amount_no,Payment_of_Min_Amount_yes,Payment_Behaviour_high_spent_medium_value_payments,Payment_Behaviour_high_spent_small_value_payments,Payment_Behaviour_low_spent_large_value_payments,Payment_Behaviour_low_spent_medium_value_payments,Payment_Behaviour_low_spent_small_value_payments,Payment_Behaviour_nan
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,1911412.0,1.824843e+16,3.0,4.0,...,True,False,True,False,False,True,False,False,False,False
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,1911412.0,NaN,3.0,4.0,...,False,False,True,False,False,False,True,False,False,False
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,1911412.0,NaN,3.0,4.0,...,False,False,True,False,False,False,False,True,False,False